script:
  - export REPO=pinholecamera/backend
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; elif [[ $TRAVIS_PULL_REQUEST == "false" ]]; then echo $TRAVIS_BRANCH | sed -e 's,/,-,g'; else echo $TRAVIS_PULL_REQUEST_BRANCH | sed -e 's,/,-,g'; fi`
  - docker build -t $REPO:$TAG -f Dockerfile .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PWD
  - docker push $REPO:$TAG;

notifications:
  email: false